GET http://localhost:3000/hello


###
//쿼리 스트링: ?뒤에 오는 내용을 말함
GET http://localhost:3000/tasks?sort=oldest&count=3

###
//dynamic URL
GET http://localhost:3000/tasks/6683ee8da681c246201d31a1


//Group api
###
//POST: 새로운 그룹 등록
POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "name": "테스트그룹2",
  "password": "123",
  "isPublic": true,
  "imageUrl": "image.pdf",
  "introduction": "소개글1"
}

###
//GET: 기존 그룹 조회
GET http://localhost:3000/api/groups

//PUT: 기존 그룹 수정
###
PUT http://localhost:3000/api/groups/66e56dccefc72088053d0255
Content-Type: application/json

{
  "name": "새로운 그룹 이름",
  "password": "새로운 비밀번호",
  "imageUrl": "새로운 이미지 URL",
  "isPublic": true,
  "introduction": "새로운 소개"
}

###
DELETE http://localhost:3000/api/groups/66e95239e754f571b5d0b2f4


###
//GET: 기존 그룹 조회
GET http://localhost:3000/api/groups/66e56dccefc72088053d0255


###
//POST: 그룹 비밀번호 검증
POST http://localhost:3000/api/groups/66e56dccefc72088053d0255/verify-password
Content-Type: application/json

{
  "password": "새로운 비밀번호"
}


//User api

### POST: 회원가입
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123"
}

### POST: 로그인
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}

### POST: 로그아웃
POST http://localhost:3000/api/user/logout
Content-Type: application/json

{}


//post api
### POST: 게시글 등록
POST http://localhost:3000/api/groups/66e9750617856a39e2a3310b/posts
Content-Type: application/json

{
  "nickname": "testuser",
  "title": "게시글 2",
  "content": "내용 2",
  "postPassword": "123",
  "groupPassword": "123",
  "imageUrl": "http://example.com/image.jpg",
  "tags": ["tag1", "tag2"],
  "location": "Test Location",
  "moment": "2024-02-21",
  "isPublic": true
}

### GET: 게시글 목록 조회
GET http://localhost:3000/api/groups/66e9750617856a39e2a3310b/posts

### PUT: 게시글 수정 테스트
PUT http://localhost:3000/api/posts/66ea372b65fdf41c280653af
Content-Type: application/json

{
  "nickname": "updated nickname",
  "title": "updated title",
  "content": "updated content",
  "postPassword": "123",
  "imageUrl": "https://example.com/updated-image.jpg",
  "tags": ["tag1", "tag2"],
  "location": "updated location",
  "moment": "2024-02-21",
  "isPublic": true
}

### DELETE: 게시글 삭제
DELETE http://localhost:3000/api/posts/66ea3bf9b7cf9050f9562203
Content-Type: application/json

{
  "postPassword": "123"
}

### GET: 게시글 상세 정보 조회
GET http://localhost:3000/api/posts/66ea3e9f577baaf1ab0db45f
Content-Type: application/json

### POST: 게시글 비밀번호 검증
POST http://localhost:3000/api/posts/66ea3e9f577baaf1ab0db45f/verify-password
Content-Type: application/json

{
	"password": "123"
}

### GET: 게시글 공개 여부 확인
GET http://localhost:3000/api/posts/66ea3e9f577baaf1ab0db45f/is-public

### POST: 게시글에 댓글 등록
POST http://localhost:3000/api/posts/66ea3e9f577baaf1ab0db45f/comments
Content-Type: application/json

{
  "nickname": "testuser",
  "content": "This is a test comment.",
  "password": "123"
}

### GET: 게시글 댓글 목록 조회
GET http://localhost:3000/api/posts/66ea3e9f577baaf1ab0db45f/comments?page=1&limit=10
