GET http://localhost:3000/hello


###
//쿼리 스트링: ?뒤에 오는 내용을 말함
GET http://localhost:3000/tasks?sort=oldest&count=3

###
//dynamic URL
GET http://localhost:3000/tasks/6683ee8da681c246201d31a1

###
//POST Request
POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "name": "테스트그룹1",
  "password": "123",
  "isPublic": true,
  "imageUrl": "image.pdf",
  "introduction": "소개글1"
}

###
//GET
GET http://localhost:3000/api/groups


###
PATCH  http://localhost:3000/tasks/1
Content-Type: application/json

{
  "isComplete": true
}

###
//delete는 body가 필요 없음
DELETE  http://localhost:3000/tasks/1